# Site settings

#Company Info
title: Sterling Electrical Contractors
company: Sterling Electrical Contractors
license: STERLEC859MS
email: info@secseattle.com
phone_number: (425) 774-1903
address: 6125 200th St SW, Lynnwood, WA 98036
city: Lynnwood, WA
hours: "8am - 4pm"

#Social network usernames
github_username: "secseattle"
linked_in: "sterling-electrical-contractors"
yelp_username: "sterling-electrical-contractors-seattle"

############## Don't Edit below this line ####################
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "secseattle.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Custom Variables
path:
  plugins: "assets/plugins"
  css: "assets/css"
  js: "assets/js"
  images: "assets/images"

# Custom Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  careers:
    output: true
    permalink: /career/:path/
  services:
    output: true
    permalink: /services/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
