# Site settings
title: Sterling Electrical Contractors | Seattle
email: aaron@secseattle.com
description: Sterling Electrical Contractors provides electrical and excavation work for commercial and residential.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "secseattle.github.io" # the base hostname & protocol for your site
github_username: "secseattle"
phone_number: (206)-123-4567
address: 123 Main Street, Everett, WA 98290
total_clients: 200
total_projects: 300

# Build settings
markdown: kramdown

# Custom Variables
path:
  plugins: "assets/plugins"
  css: "assets/css"
  js: "assets/js"
  images: "assets/images"

# Custom Collections
collections:
  members:
    output: true
  clients:
    output: true
  projects:
    output: true
  jobs:
    output: true
